### ISSUE TITLE
Compatible with mono-chrome 8x8 matrix ?

### ISSUE THREAD

**Issue by weboide** [giladaya/arduino-particle-sys#2]
This looks like a great library! But is this compatible a mono-chrome 8x8 matrix? Or would there be an easy way to make it compatible? The different color selection would obviously be ignored.

**Comment by giladaya** [comment]
It is not currently compatible with a monochrome matrix, but the source can be adjusted.
The issue is that I'm not sure if the effect will hold with only one color, I guess you'll need to try to know.
There have been some relevant comments on the project's instructable which you can check out here: http://www.instructables.com/id/Low-resolution-display-done-right/
